#
# загружаем maven
#
FROM maven:3.6.3-jdk-8 as build
#
# устанавливаем каталог с приложением
#
ENV PROJECT_DIR=/app
RUN mkdir -p $PROJECT_DIR
WORKDIR $PROJECT_DIR
#
# копируем приложение в образ 
#
COPY /config $PROJECT_DIR
#
# собираем приложение
#
RUN mvn -DstkipTests=true clean package

#
# заргужаем производственный образ
#
FROM openjdk:8-jdk
ENV PROJECT_DIR=/app
RUN mkdir -p $PROJECT_DIR
WORKDIR $PROJECT_DIR
COPY --from=build /app/target/config-2.1.3.RELEASE.jar  $PROJECT_DIR/config.jar

#
# монтируем тома
#
VOLUME ["/config.configuration"]
VOLUME ["/otus.configurations"]
#
# запускаем микросервис
#
CMD [ "java", "-Dspring.config.location=/config.configuration/application.yml", "-jar", "config.jar"]